theme: jekyll-theme-minimal
title: the Polygons plot
description: Description of Polygons plot to visualize multivariate ranges
logo: images/polygons_plot_logo.png
show_downloads: true
google_analytics: G-193ZJ31TZB
