theme: jekyll-theme-minimal
title: the Polygons plot
description: Welcome to the repository describing the multivariate range visualization Polygons plot! Polygons plot are designed to show 3 to 6 variables simultaneously showcasing the min-max and average for each. Polygons plot have been ideated by Donato Giovannelli.
logo: images/polygons_plot_logo.png
show_downloads: false
google_analytics: G-193ZJ31TZB
